version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432"
  node:
    image: node:latest
    depends_on:
      - db
    ports:
      - "4000:4000"
  # app:
  #   container_name: docker-node-postgresql
  #   restart: always
  #   build: .
  #   ports:
  #     - "80"
  #   links:
  #     - db
  # db:
  #   container_name: postgres-container-server
  #   image: postgres:12.1
  #   ports:
  #     - "5432"
  #   restart: always
